trino:
  outputs:
    dev:
      type: trino
      method: none
      user: dbt
      password: ''
      catalog: hive
      host: "{{ env_var('TRINO_HOST') }}"
      port: "{{ env_var('TRINO_PORT') | int }}"
      schema: refined
      threads: 1
  target: dev
