version: '3.9'

services:
  metabase:
    build: ./metabase
    container_name: datalake-metabase
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    ports:
      - 3000:3000
    volumes:
      - ./metabase:/metabase-data
    networks:
      - datalake-network
    restart: always

networks:
  datalake-network:
    name: ${NETWORK_MODE}
    external: true