version: '3.9'

x-hive-metastore-uri: &hive-metastore-uri thrift://datalake-hive-metastore:9083

x-s3-auth: &s3-auth
  S3_ENDPOINT: http://datalake-minio:9000
  S3_ACCESS_KEY: ${MINIO_ROOT_USER}
  S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD}

services:
  minio:
    image: minio/minio:latest
    container_name: datalake-minio
    hostname: datalake-minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - datalake-minio-volume:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ADDRESS: :9000
      MINIO_CONSOLE_ADDRESS: :9001
    command:
      - server
      - /data
    networks:
      - datalake-network

  hive-metastore-db:
    image: postgres:11
    container_name: datalake-hive-metastore-db
    hostname: datalake-hive-metastore-db
    ports:
      - 5432:5432
    volumes:
      - datalake-hive-metastore-db-volume:/var/lib/postgresql/data
    environment:    
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    networks:
      - datalake-network

  hive-metastore:
    build: ./hive
    container_name: datalake-hive-metastore
    hostname: datalake-hive-metastore
    ports:
      - 9083:9083
    volumes:
      - datalake-hive-metastore-volume:/opt/hive/data/warehouse
    environment:
      <<: *s3-auth
      DB_DRIVER: postgres
      SERVICE_NAME: metastore
      HIVE_METASTORE_URI: *hive-metastore-uri
      HIVE_METASTORE_DB_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_DB_URL: jdbc:postgresql://datalake-hive-metastore-db:5432/${POSTGRES_DB}
      HIVE_METASTORE_DB_USER: ${POSTGRES_USER}
      HIVE_METASTORE_DB_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - datalake-network
    restart: always
    depends_on:
      - hive-metastore-db
      - minio

  trino:
    image: trinodb/trino:426
    container_name: datalake-trino
    hostname: datalake-trino
    ports:
      - 8081:8080
    volumes:
      - ./trino/catalog:/etc/trino/catalog:ro
    environment:
      <<: *s3-auth
      HIVE_METASTORE_URI: *hive-metastore-uri
    networks:
      - datalake-network
    depends_on:
      - hive-metastore

  spark-master:
    image: datalake-spark-image
    build:
      context: ./spark
      args:
        <<: *s3-auth
        HIVE_METASTORE_URI: *hive-metastore-uri
        SPARK_MASTER_URL: spark://datalake-spark-master:7077
    container_name: datalake-spark-master
    hostname: datalake-spark-master
    environment: &spark-env
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: 'no'
      SPARK_RPC_ENCRYPTION_ENABLED: 'no'
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: 'no'
      SPARK_SSL_ENABLED: 'no'
      SPARK_USER: spark
    ports:
      - 8082:8080
    working_dir: /usr/app
    networks:
      - datalake-network

  spark-worker:
    image: datalake-spark-image
    environment:
      <<: *spark-env
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://datalake-spark-master:7077
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 1
    networks:
      - datalake-network
    depends_on:
      - spark-master

volumes:
  datalake-minio-volume:
    driver: local
  datalake-hive-metastore-db-volume:
    driver: local
  datalake-hive-metastore-volume:
    driver: local

networks:
  datalake-network:
    name: datalake-network
    driver: bridge
